//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 4.0.30319.17351
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData
{


    public partial class ForeignKeyFilter
    {

        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;
    }
}
